

name: Testes

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14.1
        cache: 'npm'
        
    - run: npm install
    - run: npm run cy:run
      continue-on-error: true
    - run: npm run report:merge
    - run: npm run report:mocha
